name: Deploy Monitoring Stack

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'

            set -e

            PROJECT_DIR="/home/ubuntu/project/assignment-8"

            echo "👉 Checking project directory..."

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "⚠ Repo not found, cloning..."
              rm -rf /home/ubuntu/project
              mkdir -p /home/ubuntu/project
              git clone https://github.com/tawhid3482/assignment-8.git $PROJECT_DIR
            fi

            cd $PROJECT_DIR

            echo "👉 Pulling latest code..."
            git pull origin main

            echo "👉 Running install script..."
            if [ -f monitoring/install.sh ]; then
              bash monitoring/install.sh
            else
              echo "❌ install.sh not found"
              exit 1
            fi

            echo "✅ Deployment successful!"

          EOF